"use client";

import { useMemo, useRef, useState } from "react";
import readXlsxFile from "read-excel-file/browser";

type Sector = "Technologia" | "Finanse" | "Zdrowie" | "Konsumpcja" | "Przemysł" | "Energia" | "Nieruchomości" | "ETF" | "Inne";
type Position = { id:string; symbol:string; name:string; sector:Sector; assetClass:string; quantity:number; cost:number; value:number; currency:string };
type CashEvent = { id:string; date:string; type:string; symbol:string; comment:string; amount:number };
type ClosedTrade = { id:string; date:string; symbol:string; side:string; volume:number; result:number };
type PortfolioData = { positions:Position[]; cash:CashEvent[]; trades:ClosedTrade[]; source:string };

const sectors: Sector[] = ["Technologia","Finanse","Zdrowie","Konsumpcja","Przemysł","Energia","Nieruchomości","ETF","Inne"];
const today = new Date();
const iso = (date:Date) => date.toISOString().slice(0,10);
const dateBack = (months:number, day=12) => iso(new Date(today.getFullYear(),today.getMonth()-months,day));

const demoData: PortfolioData = {
  source:"Portfel demonstracyjny",
  positions:[
    {id:"p1",symbol:"MSFT.US",name:"Microsoft",sector:"Technologia",assetClass:"Akcje",quantity:7,cost:9864,value:12462,currency:"PLN"},
    {id:"p2",symbol:"CSPX.UK",name:"iShares Core S&P 500",sector:"ETF",assetClass:"ETF",quantity:11,cost:11840,value:13776,currency:"PLN"},
    {id:"p3",symbol:"PKO.PL",name:"PKO Bank Polski",sector:"Finanse",assetClass:"Akcje",quantity:120,cost:5760,value:6828,currency:"PLN"},
    {id:"p4",symbol:"NOVO-B.DK",name:"Novo Nordisk",sector:"Zdrowie",assetClass:"Akcje",quantity:12,cost:5140,value:4632,currency:"PLN"},
    {id:"p5",symbol:"XOM.US",name:"Exxon Mobil",sector:"Energia",assetClass:"Akcje",quantity:9,cost:3720,value:4023,currency:"PLN"},
    {id:"p6",symbol:"O.US",name:"Realty Income",sector:"Nieruchomości",assetClass:"REIT",quantity:14,cost:3180,value:3374,currency:"PLN"},
  ],
  cash:[
    {id:"c1",date:dateBack(1,18),type:"DIVIDENT",symbol:"O.US",comment:"O.US USD 0.2685 / SHR",amount:14.74},
    {id:"c2",date:dateBack(1,18),type:"Withholding Tax",symbol:"O.US",comment:"O.US USD WHT 15%",amount:-2.21},
    {id:"c3",date:dateBack(2,10),type:"DIVIDENT",symbol:"MSFT.US",comment:"MSFT.US USD 0.83 / SHR",amount:23.61},
    {id:"c4",date:dateBack(2,10),type:"Withholding Tax",symbol:"MSFT.US",comment:"MSFT.US USD WHT 15%",amount:-3.54},
    {id:"c5",date:dateBack(3,18),type:"DIVIDENT",symbol:"O.US",comment:"O.US USD 0.2680 / SHR",amount:14.48},
    {id:"c6",date:dateBack(3,18),type:"Withholding Tax",symbol:"O.US",comment:"O.US USD WHT 15%",amount:-2.17},
    {id:"c7",date:dateBack(4,22),type:"DIVIDENT",symbol:"PKO.PL",comment:"PKO.PL PLN 5.48 / SHR",amount:657.6},
    {id:"c8",date:dateBack(5,18),type:"DIVIDENT",symbol:"O.US",comment:"O.US USD 0.2675 / SHR",amount:14.22},
    {id:"c9",date:dateBack(5,18),type:"Withholding Tax",symbol:"O.US",comment:"O.US USD WHT 15%",amount:-2.13},
    {id:"c10",date:dateBack(8,10),type:"DIVIDENT",symbol:"MSFT.US",comment:"MSFT.US USD 0.83 / SHR",amount:22.94},
    {id:"c11",date:dateBack(8,10),type:"Withholding Tax",symbol:"MSFT.US",comment:"MSFT.US USD WHT 15%",amount:-3.44},
    {id:"c12",date:dateBack(14,4),type:"Deposit",symbol:"",comment:"Wpłata środków",amount:30000},
  ],
  trades:[
    {id:"t1",date:dateBack(2,4),symbol:"AAPL.US",side:"SELL",volume:5,result:1240.4},
    {id:"t2",date:dateBack(6,21),symbol:"CDR.PL",side:"SELL",volume:18,result:-416.2},
    {id:"t3",date:dateBack(10,8),symbol:"VWCE.DE",side:"SELL",volume:4,result:583.6},
  ],
};

const money = (value:number,digits=0) => new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",maximumFractionDigits:digits,minimumFractionDigits:digits}).format(value);
const number = (value:number,digits=2) => new Intl.NumberFormat("pl-PL",{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(value);
const dateLabel = (value:string) => new Intl.DateTimeFormat("pl-PL",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));
const norm = (value:unknown) => String(value??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const num = (value:unknown) => { if(typeof value==="number") return value; const clean=String(value??"").replace(/\s/g,"").replace(/[^0-9,.-]/g,""); const normalized=clean.includes(",")&&!clean.includes(".")?clean.replace(",","."):clean.replace(/,/g,""); return Number(normalized)||0 };
const asDate = (value:unknown) => { if(value instanceof Date)return iso(value); if(typeof value==="number")return iso(new Date(Date.UTC(1899,11,30+value))); const s=String(value??"").trim(); const dm=s.match(/(\d{1,2})[./-](\d{1,2})[./-](\d{4})/); if(dm)return `${dm[3]}-${dm[2].padStart(2,"0")}-${dm[1].padStart(2,"0")}`; const parsed=new Date(s); return Number.isNaN(parsed.getTime())?iso(today):iso(parsed) };
const sectorFor = (symbol:string):Sector => { const s=symbol.toUpperCase(); if(/CSPX|VWCE|IWDA|ETF|SPY|QQQ|IUIT/.test(s))return"ETF"; if(/MSFT|AAPL|NVDA|GOOG|META|AMD|ASML|CDR/.test(s))return"Technologia"; if(/PKO|PEO|ING|JPM|BAC|V|MA/.test(s))return"Finanse"; if(/NOVO|JNJ|PFE|MRK|ABBV/.test(s))return"Zdrowie"; if(/XOM|CVX|SHEL|ORLEN|PKN/.test(s))return"Energia"; if(/O\.US|PLD|AMT|REIT/.test(s))return"Nieruchomości"; return"Inne" };
const pick = (map:Record<string,number>,names:string[]) => { for(const name of names)if(map[name]!==undefined)return map[name]; return -1 };

function parseRows(rows:unknown[][],sheetName:string,target:PortfolioData){
  const normalized=rows.map(row=>row.map(norm));
  const headerIndex=normalized.findIndex(row=>row.includes("symbol")&&(row.includes("amount")||row.includes("kwota")||row.includes("gross p/l")||row.includes("wynik brutto")||row.includes("purchase value")||row.includes("wartosc zakupu")));
  if(headerIndex<0)return;
  const headers:Record<string,number>={}; normalized[headerIndex].forEach((header,index)=>{if(header)headers[header]=index});
  const idx={symbol:pick(headers,["symbol","instrument","instrument finansowy"]),type:pick(headers,["type","typ"]),time:pick(headers,["time","czas","close time","czas zamkniecia","open time","czas otwarcia"]),closeTime:pick(headers,["close time","czas zamkniecia"]),comment:pick(headers,["comment","komentarz"]),amount:pick(headers,["amount","kwota"]),volume:pick(headers,["volume","wolumen"]),purchase:pick(headers,["purchase value","wartosc zakupu"]),market:pick(headers,["market value","wartosc rynkowa","market price","cena rynkowa"]),gross:pick(headers,["gross p/l","wynik brutto"]),commission:pick(headers,["commission","prowizja"]),swap:pick(headers,["swap"])};
  const dataRows=rows.slice(headerIndex+1).filter(row=>row.some(cell=>String(cell??"").trim()));
  const isCash=idx.amount>=0; const isClosed=/closed|zamkniet/.test(norm(sheetName))||idx.closeTime>=0;
  if(isCash)dataRows.forEach((row,i)=>{const type=String(row[idx.type]??"").trim();const amount=num(row[idx.amount]);if(!type&&!amount)return;target.cash.push({id:`cash-${sheetName}-${i}`,date:asDate(row[idx.time]),type,symbol:String(row[idx.symbol]??"").trim(),comment:String(row[idx.comment]??"").trim(),amount})});
  else if(isClosed)dataRows.forEach((row,i)=>{const symbol=String(row[idx.symbol]??"").trim();if(!symbol)return;const result=num(row[idx.gross])+num(row[idx.commission])+num(row[idx.swap]);target.trades.push({id:`trade-${sheetName}-${i}`,date:asDate(row[idx.closeTime>=0?idx.closeTime:idx.time]),symbol,side:String(row[idx.type]??"").trim(),volume:num(row[idx.volume]),result})});
  else dataRows.forEach((row,i)=>{const symbol=String(row[idx.symbol]??"").trim();if(!symbol)return;const cost=Math.abs(num(row[idx.purchase]));const gross=num(row[idx.gross]);let value=idx.market>=0?Math.abs(num(row[idx.market])):0;if(!value||(value<100&&cost>100))value=cost+gross;target.positions.push({id:`position-${sheetName}-${i}`,symbol,name:symbol.replace(/\.[A-Z]+$/i,""),sector:sectorFor(symbol),assetClass:sectorFor(symbol)==="ETF"?"ETF":"Akcje",quantity:num(row[idx.volume]),cost,value:value||cost,currency:"PLN"})});
}

function csvRows(text:string):string[][]{const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const delimiter=(lines[0]?.match(/;/g)?.length??0)>(lines[0]?.match(/,/g)?.length??0)?";":",";return lines.map(line=>{const result:string[]=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){cell+='"';i++}else if(char==='"')quoted=!quoted;else if(char===delimiter&&!quoted){result.push(cell);cell=""}else cell+=char}result.push(cell);return result})}

function Donut({items,total}:{items:{label:string;value:number;color:string}[];total:number}){let cursor=0;const stops=items.map(item=>{const start=cursor;cursor+=total?item.value/total*360:0;return`${item.color} ${start}deg ${cursor}deg`}).join(", ");return <div className="donut" style={{background:`conic-gradient(${stops||"#e4e6df 0 360deg"})`}}><div className="donut-hole"><span>Wartość</span><strong>{money(total)}</strong></div></div>}

export default function Home(){
  const [data,setData]=useState<PortfolioData>(demoData);
  const [view,setView]=useState<"pulpit"|"dywidendy"|"historia">("pulpit");
  const [allocation,setAllocation]=useState<"firma"|"sektor"|"klasa">("firma");
  const [importing,setImporting]=useState(false); const [notice,setNotice]=useState(""); const [dragging,setDragging]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const totalValue=data.positions.reduce((s,p)=>s+p.value,0),totalCost=data.positions.reduce((s,p)=>s+p.cost,0),openProfit=totalValue-totalCost,realized=data.trades.reduce((s,t)=>s+t.result,0);
  const dividends=data.cash.filter(c=>/divident|dividend|dywidend/i.test(c.type)); const taxes=data.cash.filter(c=>/withholding|podatek.*zrodl/i.test(norm(c.type))); const divGross=dividends.reduce((s,d)=>s+d.amount,0),divNet=divGross+taxes.reduce((s,t)=>s+t.amount,0);
  const forecast=useMemo(()=>{const grouped=new Map<string,CashEvent[]>();dividends.forEach(e=>grouped.set(e.symbol||"PORTFEL",[...(grouped.get(e.symbol||"PORTFEL")||[]),e]));const events:{date:string;symbol:string;gross:number;net:number;confidence:string}[]=[];grouped.forEach((rows,symbol)=>{const sorted=[...rows].sort((a,b)=>+new Date(a.date)-+new Date(b.date));const gaps=sorted.slice(1).map((r,i)=>(+new Date(r.date)-+new Date(sorted[i].date))/86400000);const median=gaps.length?[...gaps].sort((a,b)=>a-b)[Math.floor(gaps.length/2)]:365;const step=median<70?31:median<150?91:median<260?182:365;const last=sorted.at(-1)!;const tax=data.cash.filter(c=>c.symbol===symbol&&/withholding|podatek.*zrodl/i.test(norm(c.type))).at(-1)?.amount??0;let next=new Date(last.date),guard=0;while(next<=today&&guard++<24)next=new Date(next.getTime()+step*86400000);const end=new Date(today.getFullYear()+1,today.getMonth(),today.getDate());while(next<=end&&events.length<50){events.push({date:iso(next),symbol,gross:last.amount,net:Math.max(0,last.amount+tax),confidence:gaps.length>=2?"wyższa":"orientacyjna"});next=new Date(next.getTime()+step*86400000)}});return events.sort((a,b)=>+new Date(a.date)-+new Date(b.date))},[data.cash,dividends]);
  const forecastTotal=forecast.reduce((s,i)=>s+i.net,0);
  const allocationItems=useMemo(()=>{const map=new Map<string,number>();data.positions.forEach(p=>{const key=allocation==="firma"?p.symbol:allocation==="sektor"?p.sector:p.assetClass;map.set(key,(map.get(key)||0)+p.value)});const colors=["#2e6b4f","#e3a73a","#26342e","#8bb29e","#e4774f","#aeb5a8","#697b70","#d4c6a6"];return[...map.entries()].sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label,value,color:colors[i%colors.length]}))},[data.positions,allocation]);
  async function importFile(file?:File){if(!file)return;setImporting(true);setNotice("");const next:PortfolioData={positions:[],cash:[],trades:[],source:file.name};try{if(/\.csv$/i.test(file.name))parseRows(csvRows(await file.text()),file.name,next);else{const sheets=await readXlsxFile(file);for(const sheet of sheets)parseRows(sheet.data as unknown[][],sheet.sheet,next)}if(!next.positions.length&&!next.cash.length&&!next.trades.length)throw new Error("nie znaleziono tabel XTB");setData(next);setNotice(next.positions.length?`Gotowe — wczytano ${next.positions.length} pozycji i ${next.cash.length+next.trades.length} operacji.`:"Historia wczytana. Ten raport nie zawiera otwartych pozycji — do pełnej wyceny dodaj eksport „OPEN POSITION”.")}catch(error){setNotice(`Nie udało się odczytać pliku: ${error instanceof Error?error.message:"nieznany format"}. Spróbuj eksportu XLSX z xStation.`)}finally{setImporting(false)}}
  function updateSector(id:string,sector:Sector){setData(current=>({...current,positions:current.positions.map(p=>p.id===id?{...p,sector}:p)}))}
  const history=[...data.trades.map(t=>({id:t.id,date:t.date,type:"Zamknięcie pozycji",symbol:t.symbol,detail:`${t.side} · ${number(t.volume)} szt.`,amount:t.result})),...data.cash.map(c=>({id:c.id,date:c.date,type:c.type,symbol:c.symbol,detail:c.comment||"Operacja gotówkowa",amount:c.amount}))].sort((a,b)=>+new Date(b.date)-+new Date(a.date));
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">K</span><span>KAPITAŁ<small>prywatny portfel</small></span></div><nav aria-label="Główna nawigacja"><button className={view==="pulpit"?"active":""} onClick={()=>setView("pulpit")}><span>◫</span>Pulpit</button><button className={view==="dywidendy"?"active":""} onClick={()=>setView("dywidendy")}><span>↗</span>Dywidendy</button><button className={view==="historia"?"active":""} onClick={()=>setView("historia")}><span>≡</span>Historia konta</button></nav><div className="privacy"><span>●</span><div><strong>Dane zostają u Ciebie</strong><p>Plik jest liczony wyłącznie na tym urządzeniu.</p></div></div><button className="text-button" onClick={()=>setData(demoData)}>Przywróć dane demo</button></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">{data.source}</p><h1>{view==="pulpit"?"Twój portfel":view==="dywidendy"?"Dywidendy":"Historia konta"}</h1></div><div className="top-actions"><span className="as-of">Stan na dziś</span><button className="import-button" onClick={()=>fileRef.current?.click()} disabled={importing}><span>＋</span>{importing?"Wczytuję…":"Importuj XTB"}</button></div><input ref={fileRef} className="sr-only" type="file" accept=".xlsx,.xls,.csv" onChange={e=>importFile(e.target.files?.[0])}/></header>
    {notice&&<div className="notice" role="status"><span>i</span>{notice}<button onClick={()=>setNotice("")} aria-label="Zamknij">×</button></div>}
    {view==="pulpit"&&<><section className="hero-grid"><article className="value-card"><p>Wartość portfela</p><h2>{money(totalValue)}</h2><div className={`profit-pill ${openProfit<0?"negative":""}`}>{openProfit>=0?"↑":"↓"} {money(Math.abs(openProfit),2)} <span>({totalCost?number(openProfit/totalCost*100):"0,00"}%)</span></div><small>Niezrealizowany wynik na aktywach</small><div className="sparkline" aria-hidden="true">{Array.from({length:10},(_,i)=><i key={i}/>)}</div></article><article className="metric-card"><div className="metric-icon green">↗</div><p>Dywidendy netto</p><h3>{money(divNet,2)}</h3><small>Zebrane · cała historia</small><span className="micro">Brutto {money(divGross,2)}</span></article><article className="metric-card"><div className="metric-icon amber">◎</div><p>Prognoza 12 mies.</p><h3>{money(forecastTotal,2)}</h3><small>Na bazie poprzednich wypłat</small><span className="micro">{forecast.length} przewidywanych wypłat</span></article><article className="metric-card"><div className="metric-icon dark">Σ</div><p>Wynik zrealizowany</p><h3 className={realized<0?"red":""}>{money(realized,2)}</h3><small>Zamknięte transakcje</small><span className="micro">{data.trades.length} operacje</span></article></section>
    <section className="dashboard-grid"><article className="panel allocation-panel"><div className="panel-head"><div><p className="eyebrow">Struktura</p><h3>Rozkład portfela</h3></div><div className="segmented">{(["firma","sektor","klasa"] as const).map(item=><button key={item} className={allocation===item?"active":""} onClick={()=>setAllocation(item)}>{item==="firma"?"Spółka":item==="sektor"?"Sektor":"Klasa"}</button>)}</div></div><div className="allocation-body"><Donut items={allocationItems} total={totalValue}/><div className="legend">{allocationItems.slice(0,7).map(item=><div key={item.label}><span className="legend-dot" style={{background:item.color}}/><strong>{item.label}</strong><span>{totalValue?number(item.value/totalValue*100,1):"0,0"}%</span></div>)}</div></div></article><article className="panel forecast-panel"><div className="panel-head"><div><p className="eyebrow">Najbliższe 12 miesięcy</p><h3>Kalendarz wypłat</h3></div><button className="arrow-button" onClick={()=>setView("dywidendy")}>→</button></div><div className="forecast-list">{forecast.slice(0,4).map(item=><div key={`${item.symbol}-${item.date}`}><div className="date-tile"><b>{new Date(item.date).getDate()}</b><span>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(item.date))}</span></div><div><strong>{item.symbol}</strong><small>Prognoza · {item.confidence}</small></div><b>{money(item.net,2)}</b></div>)}{!forecast.length&&<div className="empty-inline">Brak historii dywidend do zbudowania prognozy.</div>}</div></article></section>
    <section className="panel positions-panel"><div className="panel-head"><div><p className="eyebrow">Aktywne pozycje</p><h3>Aktywa</h3></div><span className="count-pill">{data.positions.length} pozycji</span></div>{data.positions.length?<div className="table-wrap"><table><thead><tr><th>Instrument</th><th>Sektor</th><th>Ilość</th><th>Wartość</th><th>Śr. koszt</th><th>Wynik</th><th>Udział</th></tr></thead><tbody>{data.positions.map(p=>{const profit=p.value-p.cost;return <tr key={p.id}><td><div className="asset"><span>{p.symbol.slice(0,2)}</span><div><strong>{p.symbol}</strong><small>{p.name}</small></div></div></td><td><select value={p.sector} onChange={e=>updateSector(p.id,e.target.value as Sector)} aria-label={`Sektor ${p.symbol}`}>{sectors.map(sector=><option key={sector}>{sector}</option>)}</select></td><td>{number(p.quantity)}</td><td><strong>{money(p.value)}</strong></td><td>{money(p.cost)}</td><td className={profit>=0?"positive":"negative-text"}><strong>{profit>=0?"+":""}{money(profit)}</strong><small>{p.cost?`${profit>=0?"+":""}${number(profit/p.cost*100,1)}%`:"—"}</small></td><td><div className="weight"><span style={{width:`${totalValue?p.value/totalValue*100:0}%`}}/></div><small>{totalValue?number(p.value/totalValue*100,1):"0,0"}%</small></td></tr>})}</tbody></table></div>:<EmptyPositions onImport={()=>fileRef.current?.click()} onDemo={()=>setData(demoData)}/>}</section>
    <section className={`dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);importFile(e.dataTransfer.files[0])}} onClick={()=>fileRef.current?.click()}><span className="upload-icon">⇧</span><div><strong>Upuść kolejny eksport XTB</strong><p>XLSX, XLS lub CSV · plik nie opuszcza przeglądarki</p></div><button>Wybierz plik</button></section></>}
    {view==="dywidendy"&&<section className="subpage-grid"><article className="dividend-summary"><p className="eyebrow">Wpływy netto</p><h2>{money(divNet,2)}</h2><p>Łącznie od początku historii</p><div><span>Brutto <b>{money(divGross,2)}</b></span><span>Podatek u źródła <b>{money(Math.abs(divGross-divNet),2)}</b></span><span>Prognoza 12 mies. <b>{money(forecastTotal,2)}</b></span></div></article><article className="panel"><div className="panel-head"><div><p className="eyebrow">Prognoza</p><h3>Przyszłe wypłaty</h3></div><span className="count-pill">szacunek</span></div><div className="full-list">{forecast.map(item=><div key={`${item.symbol}-${item.date}`}><span className="status-dot forecast"/><div><strong>{item.symbol}</strong><small>{dateLabel(item.date)} · pewność {item.confidence}</small></div><b>{money(item.net,2)}</b></div>)}{!forecast.length&&<p className="empty-inline">Po imporcie historii dywidend pokażę tu prognozę.</p>}</div></article><article className="panel full"><div className="panel-head"><div><p className="eyebrow">Zaksięgowane</p><h3>Historia dywidend</h3></div><span className="count-pill">{dividends.length} wypłat</span></div><div className="full-list">{[...dividends].sort((a,b)=>+new Date(b.date)-+new Date(a.date)).map(item=><div key={item.id}><span className="status-dot"/><div><strong>{item.symbol||"Dywidenda"}</strong><small>{dateLabel(item.date)} · {item.comment}</small></div><b>{money(item.amount,2)}</b></div>)}</div></article></section>}
    {view==="historia"&&<section className="panel history-panel"><div className="history-summary"><div><span>Wszystkie operacje</span><strong>{history.length}</strong></div><div><span>Zamknięty wynik</span><strong className={realized>=0?"positive":"negative-text"}>{money(realized,2)}</strong></div><div><span>Przepływy gotówki</span><strong>{data.cash.length}</strong></div></div><div className="timeline">{history.map(item=><div key={item.id}><span className="timeline-dot"/><time>{dateLabel(item.date)}</time><div><strong>{item.type}</strong><small>{item.symbol?`${item.symbol} · `:""}{item.detail}</small></div><b className={item.amount>=0?"positive":"negative-text"}>{item.amount>=0?"+":""}{money(item.amount,2)}</b></div>)}{!history.length&&<p className="empty-inline">Brak operacji w zaimportowanym pliku.</p>}</div></section>}
    <footer><span>Kapitał</span><p>To narzędzie informacyjne — nie stanowi porady inwestycyjnej. Prognozy bazują wyłącznie na historii wypłat.</p><b>100% lokalnie</b></footer></section>
  </main>
}

function EmptyPositions({onImport,onDemo}:{onImport:()=>void;onDemo:()=>void}){return <div className="empty-positions"><div>◫</div><h4>Brakuje otwartych pozycji</h4><p>Historia XTB często zawiera tylko zamknięte transakcje. Wczytaj raport z tabelą „OPEN POSITION”, aby policzyć bieżący wynik i alokację.</p><span><button onClick={onImport}>Wczytaj raport</button><button className="secondary" onClick={onDemo}>Zobacz demo</button></span></div>}
